### ISSUE TITLE
Docs and interactive examples for byte/iterator parsing

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/fastparse#109]
We need this stuff to be discoverable and learnable, so we need docs, and possibly some interactive examples (e.g. upload a class file, we tell you what methods exist).

We do not need to duplicate all the docs for existing combinators that are shared with the normal string-parsing API and behave the same. Rather, we should only document the differences and byte/iterator-specific functionality we now have available, and rely on small-examples to show how they work and larger examples (similar to our Math/Json parser) to illustrate how things work when put together.

**Comment by vovapolu** [comment]
@lihaoyi  #113

**Comment by lihaoyi** [comment]
I'm going to call this done. Though we may have additional polish work to make the docs super-awesome, #113 and #114 have got us most of the way there
