### ISSUE TITLE
Explore using scodec.bits.ByteVector or akka.util.ByteString instead of Array[Byte] for byte parsing

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/fastparse#126]
It seems the @mpilquist's `scodec.bits.ByteVector` and the `akka.util.ByteString` classes are relatively lightweight, has no dependencies, and do everything I want `Array[Byte]` to do but doesn't. Things like

- Immutability
- Structural-equality

Also, it seems to have a bunch of good design decisions baked into it, that would be lacking in any naive immutable-equalable-array-thing we implement ourselves:

- "Efficient-ish" appends, through hidden mutability
- "Fast-ish" conversions to Arrays
- Some amount of structural sharing (?)
- Lots of useful operations with decent performance

Downsides of `scodec.bits.ByteVector` include the fact that it's pretty poorly documented, with only 3 pages of half-baked docs for >4000 lines of code with tons of API surface area. If we take a dependency on this, we will have to put in the grunt work to write tons and tons of documentation ourselves to bring it up to standard.

`akka.util.ByteString` is even more lightweight, but has the downside that it's not documented at all, and not even published, so we'd need to vendor a copy of their class definition in our project.

Normally I would want to push out 0.4.0 first before taking on large changes like this, because it's already taken too long with no releases over the summer. Nevertheless, this is a fundamental enough change that if we make this change out after releasing `fastparse.bytes` in 0.4.0, it will break everyone's parsers and they will need to update all their code anyway. Might aswell do the investigation up front, decide whether or not to implement it (and maybe implement it), before we release 0.4.0 and announce it to the world.

**Comment by mpilquist** [comment]
I'm happy to support this effort in any way I can. The docs on scodec.org are very light and never really got underway. On the other hand, the ScalaDoc should be fairly comprehensive.

**Comment by lihaoyi** [comment]
This has happened #127
