### ISSUE TITLE
Any plans to add an "exactly" method to the API?

### ISSUE THREAD

**Issue by dhensche** [lihaoyi/fastparse#128]
I've created a local implicit to add an `exactly` method that matches the parser exactly n times. Was wondering if this is something that others would like added to the Api itself? My implementations is naive and just uses the `rep` method

```scala
implicit class EnhancedParserApi[+T](parser: Parser[T]) {
  def exactly[R](n: Int)(implicit ev: Repeater[T, R]): Parser[R] = {
    parser.rep[R](min = n, max = n)
  }
}
```

**Comment by lihaoyi** [comment]
This has happened in master, as `"hello".rep(exactly = 5)` (e.g. https://github.com/lihaoyi/fastparse/blob/6e0a7d3291b510bb38db11c3f828ff8daa61fcf8/fastparse/shared/src/test/scala/fastparse/BmpTests.scala#L72). Will go out in 0.4.0

**Comment by dhensche** [comment]
cool! I just saw mention of it on your [blog](http://www.lihaoyi.com/post/EasyParsingwithParserCombinators.html) and was wondering if it was a planned feature or not.

**Comment by lihaoyi** [comment]
Ah yeah, the blog was a bit ahead of itself; it's existed in master for a while but I forgot we hadn't published 😛
