### ISSUE TITLE
Poor performance for Not

### ISSUE THREAD

**Issue by shawjef3** [lihaoyi/fastparse#150]
Profiling shows that this spends 13 seconds in fastparse.parsers.Combinators$Repeat.rec$3 before failing. I expected it to succeed.

```scala
import fastparse.all._
import fastparse.parsers.Combinators.Not

val p = P(Start ~ Not(CharIn("z")).rep ~ End)
p.parse("hi")
```

As a workaround I'm using `CharPred(c => ! "z".contains(c))`.

**Comment by lihaoyi** [comment]
You need `(Not(...) ~ AnyChar).rep` or `CharsWhile(_ != 'z')`
