### ISSUE TITLE
0.4.2 not compatible with Ammonite 0.9.9?

### ISSUE THREAD

**Issue by stanch** [lihaoyi/fastparse#156]
When running some code using fastparse 0.4.2 in Ammonite REPL 0.9.9, I got this:
```scala
java.lang.NoSuchMethodError: fastparse.all$.CharPred(Lscala/Function1;)Lfastparse/core/Parser;
```
Updating to 0.4.3 seems to have fixed the issue.

**Comment by lihaoyi** [comment]
Yeah I guess it was binary incompatible; oh wells
