### ISSUE TITLE
0.4.3 not tagged on github

### ISSUE THREAD

**Issue by oscar-stripe** [lihaoyi/fastparse#157]
it's listed here:

http://www.lihaoyi.com/fastparse/#ChangeLog

would be nice to easily find the tag on github.

**Comment by lihaoyi** [comment]
lol I don't remember which commit was 0.4.3 -.-

I guess I'll have to go dig for it

**Comment by lihaoyi** [comment]
Maybe I should go publish a new release 0.4.4 and hope nobody notices

**Comment by lihaoyi** [comment]
I assume it's 0.4.3 is https://github.com/lihaoyi/fastparse/commit/dcb44cc0ec73d0d680bc29322afb47625316a68e but don't remember for sure...

**Comment by hepin1989** [comment]
If you upgrade to 0.4.4,then I will upgrade too:)

**Comment by lihaoyi** [comment]
I've tagged 0.4.4 and 1.0.0, both if which should be *identical* to 0.4.3 except for publishing bits and pieces for scala-native. You can depend on those if you want more certainty about what code is actually running
