### ISSUE TITLE
Hierarchical parsing

### ISSUE THREAD

**Issue by jkorinth** [lihaoyi/fastparse#165]
I'm working with a language that has a highly ambiguous grammar; are there any provisions in FastParse to support hierarchical parsing, e.g., have a parser that matches a `Seq[String]` and then applies a `P[A]` to get a parser `P[Seq[A]]`? Otherwise I would need to exclude all kinds of starters in the parser for each element, if I was to use `.rep`.

**Comment by lihaoyi** [comment]
Please ask questions in the gitter channel and not the issue tracker
