### ISSUE TITLE
Fastparse binary compatibility in ecosystem

### ISSUE THREAD

**Issue by LogicalTime** [lihaoyi/fastparse#167]
I get linking errors when using scalapb and akkajs. They are on fastparse 0.4.2 and akkajs are on 0.4.4 now. 
fastparse.all$.CharsWhile() is removed between 0.4.2 and 0.4.4.
I made issues with both GitHub projects.. I told them your documentation says it's not binary compatible. Perhaps we should think about releasing a binary compatible 1.0.x.

**Comment by LogicalTime** [comment]
any thoughts on doing a binary compatible version? Scalajs seems to show linking errors when I try and use libraries with 2 different versions.

**Comment by LogicalTime** [comment]
Even a suggestion for libraries that want binary compatibility on what version to standardize off would be good. Then the odds of libraries our there using the same version of fastparse would be quite high.

**Comment by lihaoyi** [comment]
I’m probably going to cut a 1.0.0 release this weekend. Fastparse, as it
is, is basically done. We should be able to make further changes without
causing binary incompatibilities in the core library, and more ambitious
changes (e.g. fasterparser) can wait for 2.0 or be released as a separate
library

**Comment by LogicalTime** [comment]
You're amazing man. Thanks a ton.
