### ISSUE TITLE
test failures in intellij-scala in Scala community build

### ISSUE THREAD

**Issue by SethTisue** [lihaoyi/fastparse#170]
seen at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2017/consoleFull

```
[fastparse]   java.lang.Exception: target/repos/intellij-scala/scala/scala-impl/testdata/scalacTests/failed/t389
[fastparse]     java.lang.Exception: target/repos/intellij-scala/scala/scala-impl/testdata/scalacTests/failed/t3
```

**Comment by SethTisue** [comment]
ah, this failure had already occurred and we were already dealing with by excluding the test from our runs, but the file moved: https://github.com/scalacommunitybuild/fastparse/commit/08aab3212613f7ada0b885070f075bf61090c93e

**Comment by lihaoyi** [comment]
I've just pegged the versions of 3rd party libraries that are pulled in for the FastParse bulk test suites. Hopefully that will avoid further random issues from cropping up over time...

**Comment by SethTisue** [comment]
thanks, this should enable us track your master branch again — wip on that at https://github.com/scala/community-builds/pull/614
