### ISSUE TITLE
Support unicode escapes

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/fastparse#2]
They're dumb but we probably have to support them

@sirthias is there any way to override the parsing over *every single character or string* to check for these silly `\u0123` thingies? Maybe by modifying my current `wspStr` and `wspChar` thingies? I suppose I'd need to get rid of `anyOf` or `noneOf` because those don't support the stupid unicode escapes either.

I don't want to do a pre-processing stage if I can reasonably avoid it. Preprocessing will destroy all the source locations and require elaborate gymnastics to get them back.

**Comment by lihaoyi** [comment]
Unicode escapes are now supported in strings. I'm going to just punt on this in general as a #wontfix. In all the dozen projects I parsed, I think I found exactly 4 unicode escapes that dont fall in a string, all of which are in Scalac test files. Not worth my time to support this ^_^

**Comment by propensive** [comment]
Are they supported in characters, e.g. `'\u0000'`? That, I think, would clear up all of the other useful cases.
