### ISSUE TITLE
No SequencerN instances for N > 8

### ISSUE THREAD

**Issue by AlecZorab** [lihaoyi/fastparse#20]
When parsing long sections, types end up messy because there are no appropriate instances of Sequencer

**Comment by AlecZorab** [comment]
This is a great candidate for code generation in the style of https://github.com/non/cats/blob/master/project/Boilerplate.scala.

**Comment by lihaoyi** [comment]
This was fixed in 0.1.7 https://github.com/lihaoyi/fastparse/blob/master/build.sbt#L67-L92
