### ISSUE TITLE
Handling exceptions; alternatively: fail with custom error message?

### ISSUE THREAD

**Issue by netvl** [lihaoyi/fastparse#213]
I need to invoke an external method to obtain an object from a string, which could potentially fail, and I want to ensure that backtracking would work in this situation. For example:

```scala
def dateTime[_: P]: P[LocalDate] = P(CharsWhileIn("0-9\\-").!.map(LocalDate.parse))
```

Here we ensure that input contains some sequence of numbers and dashes, and pass it to `LocalDate.parse` which would do more specific parsing. However, if the input is not in the `yyyy-MM-dd` format, it would fail with an exception. Turns out, that the entire parser fails with this exception then, making it impossible to do e.g.

```scala
def number[_: P]: P[Int] = P(CharsWhileIn("0-9").!.map(_.toInt))
def dateOrNumber[_: P]: P[Any] = P(dateTime | number)
```

Here, `dateOrNumber` would fail with an exception when it is passed a string like `"123"`.

I understand that it is possible to write something like
```scala
def dateTime[_: P]: P[LocalDate] = P(CharsWhileIn("0-9\\-").!.flatMap { s =>
  Try(LocalDate.parse(s)).map(Pass).getOrElse(Fail)
})
```
But I see no way to pass the exception message to `Fail`, and anyway this seems like a very weird way to solve what seems like a common problem to me. Is there a better way to do it, or at least a way to pass an error message to the `Fail` parser?

**Comment by lihaoyi** [comment]
Perhaps you can fork the `Fail` function and make your fork take an error message?

```scala
  def Fail(implicit ctx: P[_]): P[Nothing] = {
    val res = ctx.freshFailure()
    if (ctx.verboseFailures) ctx.setMsg(ctx.index, () => "fail")
    res
  }
```
