### ISSUE TITLE
Migration path from fastparse-byte 1 to fastparse 2?

### ISSUE THREAD

**Issue by wintermute0xFF** [lihaoyi/fastparse#218]
How would you recommend I convert a fastparse 1.0 byte parser into a fastparse 2 parser? In the changelog I noticed you said you dropped support for byte parsing, so is byte parsing completely unsupported in fastparse 2? I must admit, this is a bit of a disappointment, as I am using fastparse-byte 1.0 to great effect.

Should I just stay on fastparse-byte 1.0? Will it still be maintained? 

Thanks!

Edit: Also how to find the fastparse-byte 1 documentation? I seem unable to find it.

**Comment by lihaoyi** [comment]
questions go in gitter
