### ISSUE TITLE
Support for predicate tests to indicate Success or Failure for parsers of T

### ISSUE THREAD

**Issue by russwyte** [lihaoyi/fastparse#23]
If this feature already exists I apologize for missing it.

It would be nice to have a built in construct for parsers with predicates like this:
import fastparse._
object Parser {
  def predicated[T](parser: Parser[T])(pred: T => Boolean): Parser[T] = P {
    parser.flatMap(x => if (pred(x)) Pass.map(_ => x) else Fail)
  }
  val pDigits: Parser[Int] = P(CharIn('0' to '9').rep(1).!.map(_.toInt))
  val pEven: Parser[Int] = predicated(pDigits)({x => x % 2 == 0})
  val pOdd: Parser[Int] = predicated(pDigits)({x => x % 2 != 0})
}

object Run extends App {
  import Parser._
  println(pEven.parse("123"))
  println(pEven.parse("124"))
  println(pOdd.parse("123"))
  println(pOdd.parse("124"))
}
Run...
Failure(predicated:0 / Fail:3 ..."", false)
Success(124, 3)
Success(123, 3)
Failure(predicated:0 / Fail:3 ..."", false)

**Comment by lihaoyi** [comment]
Sounds reasonable. I'd just call it `filter` ^_^

**Comment by russwyte** [comment]
That is precisely what I would suggest. :)

**Comment by lihaoyi** [comment]
Feel free to send a PR!

**Comment by russwyte** [comment]
I created PR #25 to add filter transformer.
