### ISSUE TITLE
No implicit view available from fastparse.P[Any] => fastparse.P[Unit]

### ISSUE THREAD

**Issue by PaperPlaneSoftware** [lihaoyi/fastparse#238]
`def sign[_: P] = P("+" ~ "-")`

Results in `No implicit view available from fastparse.P[Any] => fastparse.P[Unit]`. This is caused by `~`. I'm using Scala 2.13.1 with fastparse 2.2.2

**Comment by lihaoyi** [comment]
Please provide a full reproduction snippet with imports and other context, preferably in the REPL

**Comment by PaperPlaneSoftware** [comment]
https://gist.github.com/PaperPlaneSoftware/81788ac6b9fac1d3ff3cb02cd24ceb68

**Comment by lihaoyi** [comment]
You need an `import NoWhitespace._`

**Comment by PaperPlaneSoftware** [comment]
Thanks 👍
