### ISSUE TITLE
Allow failure within a map call

### ISSUE THREAD

**Issue by nrinaudo** [lihaoyi/fastparse#28]
There are some cases where we need to fail gracefully within a `map` call. As an example, I have some code that parses a charset name and needs to turn it into an instance of `java.nio.charset.Charset`. The name itself might be valid syntactically but not actually be the name of a valid `Charset`, which I can only discover in the `map` call.

I think what I'm really asking for is for is for `map` to be able to return a failing parser - that is, for `Parser` to have a `flatMap` method.

**Comment by lihaoyi** [comment]
Do you mean something like https://github.com/lihaoyi/fastparse/blob/master/fastparse/shared/src/main/scala/fastparse/ParserApi.scala#L67-L71

**Comment by nrinaudo** [comment]
I'm terribly sorry, I appear to be using an out-of-date version (0.3.0) in which it was not yet implemented. Apologies, I should have looked at the most recent source.

**Comment by lihaoyi** [comment]
No problem :)

**Comment by nrinaudo** [comment]
As a side note, it's a bit confusing that the more recent version is `0.1.7`, but there's a `0.3.0` version available in Maven.

Granted, if one follows your (well written) instructions, there is no problem, but it confuses tools such as [sbt-updates](https://github.com/rtimush/sbt-updates) (and people like who follow such tools blindly).

**Comment by FranklinChen** [comment]
I just encountered this version confusion before figuring out there really shouldn't be 0.3.0 out there.
