### ISSUE TITLE
Pattern-matching on Result produces a (spurious?) warning

### ISSUE THREAD

**Issue by jducoeur** [lihaoyi/fastparse#34]
When my code tries to match on the result of a parse, such as:
```
    dumpfileP.parse(mySQL) match {
      case Result.Success(stmts, _) => stmts
      case Result.Failure(parser, index) => displayFailure(...)
    }
```
The Scala compiler consistently kicks out a warning:
```
[warn] /home/jducoeur/GitHub/Querki/querki/scalajvm/app/querki/imexport/MySQLImport.scala:143: The outer reference in this type test cannot be checked at run time.
[warn]       case Result.Success(stmts, _) => stmts
```
This warning may be correct -- I'm honestly unsure -- but I don't care about it, and definitely don't want to see it.  My coding standards are "no warnings", so this is getting in the way of using FastParse for production code.

This can be worked around by using isInstanceOf + asInstanceOf, but that's rather boilerplatey.  A more idiomatic-Scala solution would be preferable.

**Comment by jducoeur** [comment]
Note that adding
```
import Result._
```
and removing the explicit `Result.` in the pattern matches has no effect -- the outer reference is still the same, regardless of whether it is explicit or not.

**Comment by lihaoyi** [comment]
What about

```scala
val (Success, Failure) = (Result.Success, Result.Failure)
```

=D

**Comment by jducoeur** [comment]
Interesting suggestion, but when I try:
```
    val (mySuccess, myFailure) = (Result.Success, Result.Failure)
    dumpfileP.parse(mySQL) match {
      case mySuccess(stmts, _) => stmts
      case myFailure(parser, index) => ...
    }
```
I'm still getting the same warning.  The issue must have to do with the Type itself, not how it's accessed.

**Comment by jducoeur** [comment]
What's really weird here is that this is a [known issue](https://issues.scala-lang.org/browse/SI-4440) in Scala -- but only when the inner case class is marked final.  In this case, it's not.  So I don't know why this is happening...

**Comment by jducoeur** [comment]
Effing fascinating.  I'm experimenting with creating a minimal case for this problem, and far as I can tell, the issue isn't the classes at all -- it's the way it's exporting them.  I couldn't repro the problem with simplified code until I introduced `fastparse.all`.  Continuing to experiment...

**Comment by jducoeur** [comment]
Okay, here's a more or less minimalish example that shows the warning:
```
package querki.test {
  
  import fakefastparse.all._
  
  class FastParseTests extends QuerkiTests {
    "My mock FastParse" should {
      "compile without warnings" in {
        val r:fakefastparse.core.Result[_] = Result.Failure()
        
        // Here is where the warnings come in:
        r match {
          case Result.Success() => fail("Okay, that totally didn't work")
          case Result.Failure() => println(s"This worked as expected")
        }
      }
    }
  }
}

package fakefastparse {
  package core {
    sealed trait Result[+T] {}
    
    object Result {
      case class Success[+T]() extends Result[T]
      case class Failure() extends Result[Nothing]
    }
  }
  
  trait Api {
    val Result = core.Result
  }
  
  object all extends Api
}
```
(QuerkiTests composes all the usual ScalaTest traits; restructure as desired for your preferred test harness.)

When compiled, this shows the warning on both clauses of the match.  If I change the import at top to:
```
  import fakefastparse.core._
```
the warnings go away.  (As they do if I give the fully-qualified paths for Success and Failure.)  So there are, at least, workarounds.

I suspect that you're bumping up against a bug in the compiler: it feels like the problem is that you're pushing the type-aliasing to the breaking point.  But that's just a guess: this is a pretty deep situation, and I don't know all the ins and outs.  And it's a bit concerning in general, since I know you use this aliasing approach a lot...

**Comment by jducoeur** [comment]
Your call on how to proceed with this.  If you want, I can raise it on scala-user to see if anybody's got any ideas, and open an SI for it if not...

**Comment by jducoeur** [comment]
And to be more precise and useful, adding:
```
import fastparse.core.Result._
```
and pattern-matching on Success and Failure that way seems to be the easiest workaround for this warning for the time being...

**Comment by Alain-Bearez** [comment]
This all boils down to some limitations in the inner class model of the JVM.

Some issues are open such as [SI-1419](https://issues.scala-lang.org/browse/SI-1419) and [SI-4440](https://issues.scala-lang.org/browse/SI-4440) for situations like the one at hand.

This is effectively a question of having a single import statement (with some compilation warnings) versus having no compilation warnings (with some more import statements). Instead of being registered here as an issue, it might get documented in the main Readme.

**Comment by morgen-peschke** [comment]
Please add this to the Readme, as this is still a problem after the rename to `Parsed`. 

In my particular setup, this was causing compilation to fail rather than just emit warnings, and I can't imagine that my setup is all that unique. I was going to give it about another half hour before giving up on it (the error doesn't google very well).

`import fastparse.core.Parsed._` seems to have fixed it.

As a side note: great library!

**Comment by nebasuke** [comment]
Had the same problem. ```import fastparse.core.Result``` fixed it for me.

**Comment by aradke** [comment]
In versions 0.2.x I had to use `import fastparse.core.Result`
In versions 0.3.x I had to use `import fastparse.core.Parsed`

To fix the compiler error: "_The outer reference in this type test cannot be checked at run time._"

(This is was using Scala 2.11.7 on the JVM with Java7.)
