### ISSUE TITLE
Obtain line number and column

### ISSUE THREAD

**Issue by tindzk** [lihaoyi/fastparse#35]
For debugging purposes, I would like to assign the line number and the column to my tree nodes. How do I obtain these information?

**Comment by lihaoyi** [comment]
`Index` returns the current index into the string. It's also available to custom `Parser`s if you want to do more fancy stuff. You can take the index and the input string and figure out what col/line it is based on where the newlines are.

It's conceivable that something this common can live in fastparse itself. Feel free to send a PR for a helper

```scala
def lineCol(index: Int, input: String): (Int, Int)
```
 =)

**Comment by krux02** [comment]
I want to do the same, but I have no idea, wher I can get that `Index` from.

```scala
val scalarLit: P[ScalarLit] =
    P( CharIn("-+").? ~ digitSeq ~ ("." ~ digitSeq).? ~ (CharIn("eE") ~ CharIn("-+").? ~ digitSeq).? ).!.map(x => ScalarLit(x.toDouble))
```

How do I add the index to the ScalarLit node?
