### ISSUE TITLE
parsing a Stream[Char]

### ISSUE THREAD

**Issue by cvogt** [lihaoyi/fastparse#38]
Any plans to support this? How hard would it be, what would be good places to look, if I wanted to add it? 

I have a use case where I want to parse a stream of lines that are not succeeded by a line break, but proceeded. There can be significant wait between the individual lines, so I need to parse and process a line before it's terminating new line is sent. Most line based streaming stuff breaks on that unfortunately, so I imagine a Stream[Char] would be the right thing here.

Also see https://github.com/tpolecat/atto/issues/11 which supports Streams of lines, not chars if I understand correctly

**Comment by tpolecat** [comment]
The streaming support right now just works with `Process[M, String]`, but they're not necessarily lines; they could each be one char long for instance. What kind of stream are you dealing with?

**Comment by cvogt** [comment]
@tpolecat let's move this to https://github.com/tpolecat/atto/issues/11 ?

**Comment by tpolecat** [comment]
doh! sorry. didn't notice I had hopped over to fastparse ;-)

**Comment by lihaoyi** [comment]
Parsing `Stream[Char]`s in a blocking way would be easy, just swap `String` out for `Stream[Char]` or `CharSequence` everywhere and it should work. 

Fastparse isn't likely ever going to have asynchronous "push" parsing AFAICT. The fact that it relies very heavily on plain-old-Scala control-flow means we're stuck with plain-old-Scala calling conventions and semantics.

Spinning up a new thread and parse it on that one would work for asynchrony on the JVM (not on Javascript). If you don't mind spending a thread doing it it'd work great

**Comment by lihaoyi** [comment]
One more thing: Scala `Stream[Char]` isn't the same as "streaming" as many people understand it, given it has infinite memoization and thus memory usage. 

FastParse has infinite backtracking. We also have Cuts, which should in theory allow you to discard prefixes you no longer need, but we'd need to properly integrate the usage of Cuts with discarding stream prefixes in order to make it work in a real "streaming" way.

**Comment by cvogt** [comment]
I am aware of and ok with steaming using the Stream semantics including complete memoization and parsing with infinite backtracking. Cuts sounds nice, but not important for my use case.

**Comment by cvogt** [comment]
blocking is ok, too, if that means it blocks until it found a match, then returns. I'd still need a way to start parsing again at the place where the old match ended. no idea what async push parsing is.

**Comment by lihaoyi** [comment]
When you get a match you get an `index: Int` you can use to start the next parse from. 

Async push-parsing is stuff like https://github.com/non/jawn#parsing

**Comment by cvogt** [comment]
Would you be open to a change of the type from String to Stream[Char] ? Sounds like it should give the right behaviour and allow me to build a streaming parser on top of it. I'd create the PR for the type change and probably the streaming parser later, if that works out.

**Comment by lihaoyi** [comment]
> Would you be open to a change of the type from String to Stream[Char]

How about `CharSequence` instead of `Stream[Char]`? That would save us boxing in the common case and only pay for boxing in the uncommon case

**Comment by lihaoyi** [comment]
e.g. https://github.com/lihaoyi/fastparse/issues/18

**Comment by cvogt** [comment]
the build-in conversion to CharSequence only works for IndexedSeq, which Stream is not. CharSequence looks like it's made for random access and has .length. On the other hand, no-one stops people from calling .length on a Scala stream. I suppose as long as FastParse doesn't call .length, it's fine :). We'll need to write a custom adapter from Stream to CharSequence. I wonder if def length = ??? is a more appropriate implementation than forwarding to Stream#length.

Sounds good, I'll make a PR when I get to it. No high urgency thing, but wanted to gather agreement first.

**Comment by lihaoyi** [comment]
> We'll need to write a custom adapter from Stream to CharSequence

Seems easy enough 

Merging into https://github.com/lihaoyi/fastparse/issues/18
