### ISSUE TITLE
Cuts are visually indistinct and typo-prone

### ISSUE THREAD

**Issue by Ichoran** [lihaoyi/fastparse#42]
`~! "foo"` and `~!" foo"` and `~ !"foo"` all parse, and all do different things, despite being nearly indistiguishable visually.

Either negation or the cut operator should change.  Negation could be `Not`, or cut could be `~>` or somesuch.  (`~>` because it visually suggests it's one way, and it parses with the same precedence as `~!`.)

**Comment by lihaoyi** [comment]
I understand the problem with `~!`. 

OTOH I'm also reluctant to make it `~>`; that re-uses an operator already defined in scala-parser-combinators and atto, and pretty widely used, to do something totally different. That's not great for people coming from the other two libraries, which I'd guess are a non-trivial number.

Basically anything starting with `~` will have the correct precedence; maybe something like `~/`? I don't actually know if it's worth changing, but maybe that's my thousands-of-lines-of-scala-parser-combinator-experience speaking...

**Comment by Ichoran** [comment]
Well, almost anything would be better than `~!`, since your writeup made it seem like a really good idea to use cuts, and I used them, and then was immediately bitten by the difficulty of reading and not typoing the syntax.  `~/` would be okay.  `~#` is faster to type and is more visually distinct.  `~~~` is also pretty fast to type and visually clear, though it's not so obvious it might mean no backtracking.

**Comment by Alain-Bearez** [comment]
What about ```~!~``` which would keep the idea of the classical sequence operator, only cut in the middle. This way any whitespace on either side of the central ```!``` would lead to a compile error.

**Comment by Alain-Bearez** [comment]
I implemented this alternate cut sequence operator in pull request #53, for you to check.

**Comment by lihaoyi** [comment]
Closed by #57
