### ISSUE TITLE
Unexpected string capturing of Lookahead

### ISSUE THREAD

**Issue by rintcius** [lihaoyi/fastparse#60]
```
val aa: P[String] = P("aa").!
val aaLA: P[(String, String)] = (&(aa)).! ~ aa
```

I'd have expected this to succeed, but it fails: `val Success(("aa", "aa"), _) = aaLA.parse("aa")`

Instead this succeeds: `val Success(("", "aa"), _) = aaLA.parse("aa")`

**Comment by lihaoyi** [comment]
Seems expected behavior to me. Come ask on gitter if you think I'm mistaken.

For the behavior you want, nothing is built in right now, but you can write your own `Parser[T]` that will do it. Again, come ask on gitter =P
