### ISSUE TITLE
Documentation should contain section on "When to use `P(...)`"

### ISSUE THREAD

**Issue by MartinSenne** [lihaoyi/fastparse#65]
Currently, the readme (user manual) does not contain any information of 
- why and when to wrap a parser into a `P(...)`, 
- what the "consequences" of not doing so are.

**Comment by jvparkourm** [comment]
I would like to escalate this:  If you have one or more parsers that - accidentally or otherwise - relies on implicit conversion, like:

**Comment by seanmcl** [comment]
+1

**Comment by lihaoyi** [comment]
Added to http://www.lihaoyi.com/fastparse/#Basic
