### ISSUE TITLE
Feature request: error recovery

### ISSUE THREAD

**Issue by edko99** [lihaoyi/fastparse#74]
Would it be possible to implement error recovery, like parboiled1 does (trying to synchronize the input by adding or deleting tokens from the token stream)? This would allow many more uses for fastparse, like creating very powerful editors for DSLs, in combination with scala.js and CodeMirror.

**Comment by lihaoyi** [comment]
It's probably possible but unlikely to happen.

Also, if you're asking questions, you should ask them in gitter, not on the issue tracker

**Comment by lihaoyi** [comment]
I'm closing this not because this feature would be undesirable, but because it's not sufficiently specced out to be tracked as a real work item. Feel free to experiment, see what you can come up with, and send a PR :)
