### ISSUE TITLE
true stream parsing

### ISSUE THREAD

**Issue by cvogt** [lihaoyi/fastparse#94]
Hi @vovapolu . I heard you are hacking on FastParse this summer. One thing that is similar to the changes you are doing would be support for true stream parsing. I actually opened https://github.com/lihaoyi/fastparse/pull/39 for this last year. It worked, but we never investigated the performance implications. There may be some refinements for speedup needed to avoid the control flow via exceptions. Maybe you want to take a crack at it :)?

One concrete use case I have personally would be improving Scala error messages with a streaming error message parser. Combining https://github.com/cvogt/cbt/ with https://github.com/cvogt/scalac-cosmetics/

**Comment by lihaoyi** [comment]
This is happening here #97

**Comment by cvogt** [comment]
awesome :)!!!

**Comment by vovapolu** [comment]
Last changes brought the ability to parse streaming data, though it's not perfect and even unstable, I think this issue isn't relevant yet.

**Comment by cvogt** [comment]
@vovapolu nice :). Is there a trajectory to stabilize it?

**Comment by lihaoyi** [comment]
I'm probably going to take a crack at optimizing/fully-understanding it at the end of the summer after GSOC, after which I'll publish the next stable release containing the summer's worth of changes (binary & streaming parsing)

@cvogt If you have time to publishLocal it and see how it works for your use cases right now, that would help a lot 😄

**Comment by cvogt** [comment]
probably not any time soon, but might do a follow up pr whenever I get to it in case something is missing
