### ISSUE TITLE
Support for completion

### ISSUE THREAD

**Issue by jchapuis** [lihaoyi/fastparse#98]
Hi there, how easy would it be to adapt the library to support tab completion for e.g. a REPL grammar, similarly to what is supported by the sbt parsers? Thanks

**Comment by lihaoyi** [comment]
It's possible to build a layer on top of this library to do this, but this library itself is unlikely to provide special support. 

You could, for example, parse something and looked at the `traceParsers` that failed to see what the possibilities that could let the parse continue would be. This would be a neat technique to add to the readme

**Comment by jchapuis** [comment]
Thanks a lot for your answer! I still don't see fully how to make this work. For instance, let's say I have a number of alternatives for a string literal. At the point just where that literal is expected, the user presses the tab key. The parsing fails because the required literal is missing, so I retrieve the last parser in the trace. Then I would have to introspect or "ask" this parser about what are the possible alternatives to offer them to the user. This means I somehow have to adapt the parsers or find a way to extract this information from them. Is that feasible? 
Thanks a lot for your answer, rich autocompletion is a strong requirement for me and I'm about to start implementing my own parser combinators library which embeds this notion of completion at its core, in the parser trait itself, akin to what is done in the sbt parsers.

**Comment by lihaoyi** [comment]
Something like this would work
```scala
haoyi-fastparse@
{
def flatten(p: fastparse.core.Parser[_]): Seq[fastparse.core.Parser[_]] = p match {
  case fastparse.parsers.Combinators.Either(ps@_*) => ps.flatMap(flatten)
  case fastparse.parsers.Combinators.Rule(_, p) => flatten(p())
  case fastparse.WhitespaceApi.CustomSequence(wl, p0, p, _) => flatten(p0)
  case fastparse.parsers.Combinators.Optional(p) => flatten(p)
  case fastparse.parsers.Combinators.Repeat(p, _, _, _) => flatten(p)
  case fastparse.parsers.Combinators.Sequence.Flat(p0, ps) => (p0 +: ps.map(_.p)).flatMap(flatten)
  case x => Seq(x)
}
def failure = scalaparse
  .Scala
  .CompilationUnit
  .parse("@annot Foo")
  .asInstanceOf[fastparse.core.Parsed.Failure]

failure.index
failure.extra
       .traced
       .traceParsers
       .toSeq
       .flatMap(flatten)
       .distinct
       .filter(_.isInstanceOf[fastparse.parsers.Terminals.Literal])
}
defined function flatten
defined function failure
res30_2: Int = 7
res30_3: Seq[fastparse.core.Parser[_]] = ArrayBuffer(
  "abstract",
  "final",
  "sealed",
  "implicit",
  "lazy",
  "private",
  "protected",
  "override",
  "trait",
  "case"
)
```

This flattens out the `traceParsers` and tries to find whatever is on the most LHS of those parsers. Many of them will be some kind of `fastparse.Terminals.Literal`, and you could use those for your autocomplete. 

Note that this depends 100% on your parser being strict about unnecessary backtracking (i.e. having lots of `~/`s where necessary) in order for the final `traceParsers` to be in the correct location, at the end of the input.

FastParse could possibly support more things related to this in future, or provide more guarantees about what the parser structure looks like, but for now this will have to do

**Comment by jchapuis** [comment]
Great, thanks a lot for your detailed answer, very much appreciated!
